@startuml
actor Admin 
actor Mahasiswa

usecase "Login Admin" as UC1
usecase "Login Mahasiswa" as UC2
usecase "Akses Manajemen Jadwal" as UC3
usecase "Tambah Jadwal" as UC4
usecase "Edit Jadwal" as UC5
usecase "Hapus Jadwal" as UC6
usecase "Akses Tampilan Jadwal" as UC7
usecase "Tampilkan Detail; Jadwal" as UC8
usecase "Logout" as UC9

Admin --> UC1
UC1 --> UC3
UC3 --> UC4: include
UC3 --> UC5: include
UC3 --> UC6: include
UC3 --> UC9: extend

Mahasiswa --> UC2
Mahasiswa --> UC7
Mahasiswa --> UC8
Mahasiswa --> UC9

UC1 --> UC9 : after succesful login
UC2 --> UC9 : after succesful login
@enduml